site_name: AIPOD二次开发手册
nav:
    - 项目简介: 项目简介.md
    - 逻辑概念结构: 逻辑概念结构.md
    - 二次开发教程: 二次开发教程.md
    - 非功能需求: 非功能需求.md
    - 附录(API大全): 附录.md


# mathjax
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# 作者
site_author: 'hengh'
# 主题
theme:
    name: readthedocs

copyright: '南京天洑软件有限公司'
