site_name: AIPOD二次开发手册
nav:
    - Home: index.md
    - 文档说明: 文档说明.md
    - 版本信息: 版本信息.md
    - 项目简介: 项目简介.md
    - 项目架构: 项目结构.md
    - 原型介绍: 原型介绍.md
    - 二次开发教程: 二次开发教程.md
    - 非功能需求: 非功能需求.md
    - 附录: 附录.md

# mathjax
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# 作者
site_author: 'hengh'
# 主题
theme:
    name: readthedocs
